system:
  domain: mall
  version: 1.0
  env: "dev"
  HttpPort: ":8080"
  Host: 0.0.0.0
  UploadModel: "local"

mysql:
  dialect: "mysql"
  dbHost: "mysql"
  dbPort: "3306"
  dbName: "mall_db"
  userName: "mall"
  password: "123456"
  charset: "utf8mb4"

redis:
  redisDbName: 4
  redisHost: redis
  redisPort: 6379
  redisPassword: 123456
  redisNetwork: "tcp"

token:
  accessTokenExpiry: 604800
  refreshTokenExpiry: 2592000

cache:
  cacheType: redis
  cacheEmpires: 600
  cacheWarmUp:
  cacheServer:

email:
  address: http://localhost:8080/#/vaild/email/
  smtpHost:
  smtpEmail:
  smtpPass:

encryptSecret:
  jwtSecret: "JWTSecret"
  emailSecret: "EmailSecret"
  phoneSecret: "PhoneSecret"

# aws s3 configuration
awsS3:
  bucket: your-bucket
  region: ap-southeast-1
  endpoint: ""
  s3ForcePathStyle: false
  disableSsl: false
  secretId: your-secret-id
  secretKey: your-secret-key
  baseUrl: ""
  pathPrefix: ""

local:
  path: http://localhost
  storePath: /static/upload/